#!/usr/bin/env python3
"""Convert an image to OEPL flash bitmap (LVGL CF_INDEXED_1_BIT, little-endian w/h header)."""

from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path

from PIL import Image


def pack_1bpp(img: Image.Image) -> tuple[int, int, bytes]:
    w, h = img.size
    row_bytes = math.ceil(w / 8)
    out = bytearray(row_bytes * h)
    px = img.load()
    for y in range(h):
        row = y * row_bytes
        for x in range(w):
            # Bit 1 = ink (COLOR_BLACK plane).
            if px[x, y]:
                out[row + (x // 8)] |= 1 << (7 - (x % 8))
    return w, h, bytes(out)


def to_c_array(name: str, w: int, h: int, data: bytes) -> str:
    lines = [
        "// Generated by tools/img_to_flash_bitmap.py — do not edit by hand.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"static const uint8_t {name}[] = {{",
        f"  {w & 0xFF:#04x}, {w >> 8:#04x}, {h & 0xFF:#04x}, {h >> 8:#04x},",
    ]
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        hexes = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"  {hexes},")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("input")
    ap.add_argument("-o", "--output", required=True)
    ap.add_argument("-n", "--name", default="dc34_logo")
    ap.add_argument("-W", "--width", type=int, default=120)
    ap.add_argument("-H", "--height", type=int, default=0, help="0 = same as width")
    ap.add_argument("-t", "--threshold", type=int, default=170)
    ap.add_argument("--dither", action="store_true")
    args = ap.parse_args()

    height = args.height or args.width
    im = Image.open(args.input).convert("RGBA")
    im = im.resize((args.width, height), Image.Resampling.LANCZOS)
    bg = Image.new("RGBA", im.size, (255, 255, 255, 255))
    im = Image.alpha_composite(bg, im).convert("L")
    if args.dither:
        im = im.convert("1", dither=Image.Dither.FLOYDSTEINBERG)
        im = im.point(lambda p: 0 if p else 1, mode="L")
    else:
        im = im.point(lambda p: 1 if p < args.threshold else 0, mode="1")

    w, h, data = pack_1bpp(im)
    Path(args.output).write_text(to_c_array(args.name, w, h, data))
    print(f"Wrote {args.output}: {w}x{h}, {4 + len(data)} bytes", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
